Fundamental library for mathematical and scientific computing especially used for matrices and arrays along with mathematical fucntion on arrays and vectorized operations. 

In [2]:
import numpy as np

##creating arrays using numpy

##1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)

print(arr1.shape)

[1 2 3 4 5]
(5,)


In [7]:
arr2 = np.array([1,2,3,4,5])
print(arr2.reshape((1,5)))
print(arr2.shape)

[[1 2 3 4 5]]
(5,)


In [8]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
#2d array
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
arr3.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
##inbuilt functions
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
##identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
##vectorized operations 

arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,20,30,40,50,60])

#element wise addition
print('addition:', arr1+arr2)
print('subraction:', arr1-arr2)
print('multiplication:', arr1*arr2)
print('division:', arr1/arr2)
print('equalty check',arr1 == arr2)


addition: [11 22 33 44 55 66]
subraction: [ -9 -18 -27 -36 -45 -54]
multiplication: [ 10  40  90 160 250 360]
division: [0.1 0.1 0.1 0.1 0.1 0.1]
equalty check [False False False False False False]
modulation: [1 2 3 4 5 6]


In [26]:
#universal functions - some functions which apply for the entire array.
arr = np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [43]:
##slicing and indexing operations.
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array: \n',arr)
print('array value 1st row 1st column is', arr[0][0])
print(arr[1:,2:])
print(arr[0:2,2:])

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array value 1st row 1st column is 1
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [44]:
##modifying array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [45]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [47]:
##statistical normalization

#having a std deviation of 1 and mean of 0

data = np.array([1,2,3,4,6])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean)/ std_dev
print('Normalized data', normalized_data)

Normalized data [-1.27872403 -0.69748583 -0.11624764  0.46499055  1.62746694]


In [49]:
##mean median mode
data = np.arange(1,10)
#mean
mean = np.mean(data)
print('mean',mean)

median = np.median(data)
print('median',median)

std_dev = np.std(data)
print('standard deviation', std_dev)

variance = np.var(data)
print('variance',variance)


mean 5.0
median 5.0
standard deviation 2.581988897471611
variance 6.666666666666667


In [50]:
##logical operations
data = np.arange(1,10)

print(data[data > 5])

[6 7 8 9]
